package xis.crm;

import one.xis.context.Component;
import one.xis.context.Init;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.SQLException;

@Component
public class DatabaseInitializer {
    private final DataSource dataSource;

    public DatabaseInitializer(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    @Init
    void initialize() throws SQLException {
        try (var connection = dataSource.getConnection()) {
            createSchema(connection);
            seed(connection);
            seedMissingReminders(connection);
        }
    }

    private void createSchema(Connection connection) throws SQLException {
        statement(connection, """
                create table if not exists employees (
                    user_id varchar(80) primary key,
                    preferred_username varchar(60) unique not null,
                    name varchar(120) not null,
                    password varchar(80) not null,
                    role varchar(20) not null,
                    active boolean not null
                )
                """);
        statement(connection, """
                create table if not exists customers (
                    id bigint generated by default as identity primary key,
                    name varchar(160) not null,
                    segment varchar(80) not null,
                    city varchar(80) not null,
                    email varchar(160) not null,
                    phone varchar(60) not null,
                    stage varchar(60) not null,
                    revenue int not null,
                    owner_id varchar(80) not null,
                    notes text not null,
                    constraint fk_customer_owner foreign key (owner_id) references employees(user_id)
                )
                """);
        statement(connection, """
                create table if not exists contacts (
                    id bigint generated by default as identity primary key,
                    customer_id bigint not null,
                    employee_id varchar(80) not null,
                    contact_date varchar(40) not null,
                    channel varchar(40) not null,
                    description text not null,
                    constraint fk_contact_customer foreign key (customer_id) references customers(id),
                    constraint fk_contact_employee foreign key (employee_id) references employees(user_id)
                )
                """);
        statement(connection, """
                create table if not exists follow_ups (
                    id bigint generated by default as identity primary key,
                    customer_id bigint not null,
                    employee_id varchar(80) not null,
                    due_date timestamp not null,
                    task varchar(180) not null,
                    done boolean not null,
                    constraint fk_follow_customer foreign key (customer_id) references customers(id),
                    constraint fk_follow_employee foreign key (employee_id) references employees(user_id)
                )
                """);
        statement(connection, """
                create table if not exists follow_up_reminders (
                    id bigint generated by default as identity primary key,
                    follow_up_id bigint not null,
                    employee_id varchar(80) not null,
                    due_date timestamp not null,
                    sent boolean not null,
                    done boolean not null,
                    constraint fk_reminder_follow_up foreign key (follow_up_id) references follow_ups(id),
                    constraint fk_reminder_employee foreign key (employee_id) references employees(user_id)
                )
                """);
    }

    private void seed(Connection connection) throws SQLException {
        if (count(connection, "employees") > 0) {
            return;
        }
        statement(connection, """
                insert into employees (user_id, preferred_username, name, password, role, active) values
                ('admin', 'admin', 'Ada Keller', 'admin', 'ADMIN', true),
                ('mara', 'mara', 'Mara Stein', 'demo', 'SALES', true),
                ('tom', 'tom', 'Tom Berger', 'demo', 'SALES', true)
                """);
        statement(connection, """
                insert into customers (name, segment, city, email, phone, stage, revenue, owner_id, notes) values
                ('Nordlicht Logistics', 'Enterprise', 'Hamburg', 'ops@nordlicht.example', '+49 40 100200', 'PROPOSAL', 180000, 'mara', 'Needs rollout plan for three warehouses. Procurement asks for short implementation risk note.'),
                ('Kanzlei Winter & Partner', 'Professional Services', 'Koeln', 'office@winter.example', '+49 221 22233', 'DISCOVERY', 42000, 'tom', 'Interested in secure client portal. Decision after tax season.'),
                ('Havel Energie', 'Public Sector', 'Potsdam', 'it@havel.example', '+49 331 908070', 'NEGOTIATION', 260000, 'mara', 'Strong technical fit. Legal wants data retention matrix.'),
                ('Blue Pepper Retail', 'SMB', 'Leipzig', 'hello@bluepepper.example', '+49 341 8877', 'PIPELINE', 28000, 'tom', 'Pilot starts with five shops. Keep training material compact.')
                """);
        statement(connection, """
                insert into contacts (customer_id, employee_id, contact_date, channel, description) values
                (1, 'mara', cast(current_date - 4 as varchar), 'Call', 'Discussed integration timeline and demo environment.'),
                (1, 'admin', cast(current_date - 2 as varchar), 'Email', 'Sent draft security answers and commercial outline.'),
                (2, 'tom', cast(current_date - 8 as varchar), 'Meeting', 'Collected current pain points around document handover.'),
                (3, 'mara', cast(current_date - 1 as varchar), 'Call', 'Procurement asked for final offer by Friday.'),
                (4, 'tom', cast(current_date - 5 as varchar), 'Workshop', 'Mapped shop manager onboarding flow.')
                """);
        statement(connection, """
                insert into follow_ups (customer_id, employee_id, due_date, task, done) values
                (1, 'mara', cast(current_date + 1 as timestamp), 'Send revised offer with rollout phases', false),
                (2, 'tom', cast(current_date + 5 as timestamp), 'Schedule portal demo with partners', false),
                (3, 'mara', cast(current_date + 2 as timestamp), 'Send legal data retention matrix', false),
                (4, 'tom', cast(current_date + 7 as timestamp), 'Prepare training checklist', false),
                (4, 'tom', cast(current_date - 1 as timestamp), 'Confirm pilot store list', true)
                """);
    }

    private void seedMissingReminders(Connection connection) throws SQLException {
        if (count(connection, "follow_up_reminders") > 0) {
            return;
        }
        statement(connection, """
                insert into follow_up_reminders (follow_up_id, employee_id, due_date, sent, done)
                select id, employee_id, due_date, false, false
                from follow_ups
                where done = false
                """);
    }

    private int count(Connection connection, String table) throws SQLException {
        try (var statement = connection.createStatement();
             var result = statement.executeQuery("select count(*) from " + table)) {
            result.next();
            return result.getInt(1);
        }
    }

    private void statement(Connection connection, String sql) throws SQLException {
        try (var statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }
}
